# Reference: https://github.com/marketplace/actions/setup-node-js-environment 

name: Truffle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm --version
    - name: Create .env file
      run: echo "${{ secrets.DOT_ENV }}" > .env
    - name: Install Truffle
      run: npm install truffle -g
    - name: Install Truffle Dependencies
      run: npm install      
    - name: Run Truffle Test  
      run: truffle test
    - name: Setup Python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: python --version
